// <auto-generated />
using System;
using jf_web.DataAccess;
using jf_web.Routes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace jf_web.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190317114049_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("jf_web.Controllers.Member", b =>
                {
                    b.Property<string>("Cpr")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Cpr");

                    b.ToTable("Members");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Member");
                });

            modelBuilder.Entity("jf_web.Controllers.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MemberCpr");

                    b.Property<int?>("PaymentMethodId");

                    b.HasKey("Id");

                    b.HasIndex("MemberCpr");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("jf_web.Controllers.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("jf_web.Controllers.Employee", b =>
                {
                    b.HasBaseType("jf_web.Controllers.Member");

                    b.Property<string>("Address");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("jf_web.Controllers.Membership", b =>
                {
                    b.HasOne("jf_web.Controllers.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberCpr");

                    b.HasOne("jf_web.Controllers.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");
                });
#pragma warning restore 612, 618
        }
    }
}
