// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jf_web.DataAccess;

namespace jf_web.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview3.19153.1");

            modelBuilder.Entity("jf_web.Domain.Member", b =>
                {
                    b.Property<string>("Cpr")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<int?>("TournamentPinId");

                    b.HasKey("Cpr");

                    b.HasIndex("TournamentPinId");

                    b.ToTable("Members");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Member");
                });

            modelBuilder.Entity("jf_web.Domain.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("MemberCpr");

                    b.Property<int?>("PaymentMethodId");

                    b.HasKey("Id");

                    b.HasIndex("MemberCpr");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Membership");
                });

            modelBuilder.Entity("jf_web.Domain.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod");
                });

            modelBuilder.Entity("jf_web.Domain.TournamentPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Achieved");

                    b.HasKey("Id");

                    b.ToTable("TournamentPin");
                });

            modelBuilder.Entity("jf_web.Domain.Employee", b =>
                {
                    b.HasBaseType("jf_web.Domain.Member");

                    b.Property<string>("Address");

                    b.Property<string>("Company");

                    b.Property<string>("Email");

                    b.Property<bool>("Magazine");

                    b.Property<string>("Phone");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("jf_web.Domain.Member", b =>
                {
                    b.HasOne("jf_web.Domain.TournamentPin", "TournamentPin")
                        .WithMany()
                        .HasForeignKey("TournamentPinId");
                });

            modelBuilder.Entity("jf_web.Domain.Membership", b =>
                {
                    b.HasOne("jf_web.Domain.Member", "Member")
                        .WithMany("Memberships")
                        .HasForeignKey("MemberCpr");

                    b.HasOne("jf_web.Domain.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");
                });
#pragma warning restore 612, 618
        }
    }
}
